import React, {useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {Home, Sprout, ShoppingCart, Handshake, Truck, BarChart3, Wallet, UserRound, Bell, Search, Plus, MapPin, CheckCircle2, ChevronRight, ArrowRight, ShieldCheck, BrainCircuit, Menu, X} from "lucide-react";
import {LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar} from "recharts";
import "./styles.css";

const demoListings=[
 {id:1,crop:"Wheat",farmer:"Ramesh Kumar",location:"Indore, Madhya Pradesh",qty:500,price:25,grade:"A",harvest:"12 Aug 2026",distance:42,verified:true},
 {id:2,crop:"Soybean",farmer:"Sunita Devi",location:"Ujjain, Madhya Pradesh",qty:300,price:43,grade:"A+",harvest:"15 Aug 2026",distance:68,verified:true},
 {id:3,crop:"Onion",farmer:"Mohan Lal",location:"Nashik, Maharashtra",qty:800,price:18,grade:"B+",harvest:"10 Aug 2026",distance:190,verified:true},
 {id:4,crop:"Mustard",farmer:"Amit Singh",location:"Kota, Rajasthan",qty:450,price:52,grade:"A",harvest:"08 Aug 2026",distance:110,verified:true}
];
const offers=[["AgroMart Pvt Ltd",28,96],["FreshBasket",27,91],["National Foods",29,84]];
const trend=[{m:"Mar",p:21},{m:"Apr",p:22},{m:"May",p:23},{m:"Jun",p:22},{m:"Jul",p:24},{m:"Aug",p:25}];

function App(){
 const [page,setPage]=useState("dashboard");
 const [role,setRole]=useState("farmer");
 const [mobile,setMobile]=useState(false);
 const [listed,setListed]=useState(false);
 const [accepted,setAccepted]=useState(false);
 const [search,setSearch]=useState("");
 const [toast,setToast]=useState("");
 const nav=role==="farmer"
 ? [["dashboard","Dashboard",Home],["produce","My Produce",Sprout],["offers","Buyer Offers",Handshake],["market","Market Prices",BarChart3],["orders","Orders",ShoppingCart],["logistics","Logistics",Truck],["analytics","Analytics",BarChart3]]
 : [["dashboard","Dashboard",Home],["market","Find Produce",Search],["orders","My Orders",ShoppingCart],["suppliers","Saved Suppliers",Handshake],["analytics","Price Analytics",BarChart3],["logistics","Logistics",Truck]];
 const notify=(s)=>{setToast(s);setTimeout(()=>setToast(""),2500)};
 const filtered=useMemo(()=>demoListings.filter(x=>(x.crop+" "+x.location+" "+x.farmer).toLowerCase().includes(search.toLowerCase())),[search]);

 return <div className="app">
  <aside className={"sidebar "+(mobile?"open":"")}>
   <div className="brand"><div className="logo">K</div><div><b>KrishiDirect</b><small>SIH26033 • Prototype</small></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
   <div className="rolebox"><span>Viewing as</span><select value={role} onChange={e=>{setRole(e.target.value);setPage("dashboard")}}><option value="farmer">Farmer</option><option value="buyer">Buyer</option></select></div>
   <nav>{nav.map(([id,label,Icon])=><button className={page===id?"active":""} onClick={()=>{setPage(id);setMobile(false)}} key={id}><Icon size={18}/>{label}</button>)}</nav>
   <div className="sidebottom"><button onClick={()=>notify("Profile opened")}><UserRound size={18}/>Profile</button><div className="verified"><ShieldCheck size={17}/><div><b>Verified account</b><small>Demo verification</small></div></div></div>
  </aside>
  <main>
   <header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">KrishiDirect / <b>{page[0].toUpperCase()+page.slice(1)}</b></div><div className="headright"><div className="search"><Search size={17}/><input placeholder="Search produce, buyers..." value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="iconbtn" onClick={()=>notify("3 new notifications")}><Bell size={19}/></button><div className="avatar">RK</div></div></header>
   <section className="content">
    {page==="dashboard" && <Dashboard role={role} listed={listed} accepted={accepted} setPage={setPage} notify={notify}/>}
    {page==="produce" && <Produce listed={listed} setListed={setListed} notify={notify}/>}
    {page==="market" && <Marketplace filtered={filtered} search={search} setSearch={setSearch} notify={notify}/>}
    {page==="offers" && <Offers accepted={accepted} setAccepted={setAccepted} notify={notify}/>}
    {page==="orders" && <Orders accepted={accepted}/>}
    {page==="logistics" && <Logistics accepted={accepted}/>}
    {page==="analytics" && <Analytics/>}
    {page==="suppliers" && <Suppliers/>}
   </section>
  </main>
  {toast && <div className="toast"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}

function Top({eyebrow,title,desc,children}){return <div className="top"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{children}</div>}
function Dashboard({role,listed,accepted,setPage,notify}){
 return <><div className="hero"><div><span className="pill">● LIVE PROTOTYPE • DEMO DATA</span><h1>From Farmers to Markets.<br/><span>With Fewer Middlemen.</span></h1><p>Connect farmers directly with verified buyers, discover transparent prices, and move agricultural produce through a smarter supply chain.</p><div className="actions"><button className="primary" onClick={()=>setPage(role==="farmer"?"produce":"market")}>{role==="farmer"?"Sell Your Produce":"Buy Direct"} <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setPage("market")}>Explore Marketplace</button></div></div><div className="flow"><div className="node"><Sprout/><b>Farmer</b><small>Produce</small></div><ArrowRight/><div className="node mid"><BrainCircuit/><b>KrishiDirect</b><small>Match + Price</small></div><ArrowRight/><div className="node"><ShoppingCart/><b>Verified Buyer</b><small>Demand</small></div><div className="saved">↓ Fewer unnecessary intermediaries</div></div></div>
 <div className="demo-note"><ShieldCheck size={18}/><b>Prototype Demo Data</b><span>All metrics and users shown here are fictional for the SIH presentation.</span></div>
 <div className="stats">{[["2,450+","Farmers"],["680+","Verified Buyers"],["12,500","Tonnes Listed"],["₹8.4 Cr","Transaction Value"]].map(x=><div className="stat" key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div>
 <div className="grid2"><div className="card"><div className="cardhead"><div><b>Price Transparency</b><small>Wheat • DEMO DATA</small></div><span className="green">+40% farmer share</span></div><div className="pricebars"><div><span>Farmer receives</span><b>₹15/kg</b><i style={{width:"38%"}}/></div><div><span>Direct platform</span><b>₹25/kg</b><i style={{width:"63%"}}/></div><div><span>Traditional consumer price</span><b>₹40/kg</b><i style={{width:"100%"}}/></div></div></div>
 <div className="card"><div className="cardhead"><div><b>AI Market Intelligence</b><small>Prototype recommendations</small></div><BrainCircuit className="green"/></div><div className="matches">{offers.map(o=><div className="match" key={o[0]}><div><b>{o[0]}</b><small>Wheat • 500 kg • ₹{o[1]}/kg</small></div><strong>{o[2]}%</strong></div>)}</div><button className="link" onClick={()=>setPage("offers")}>Compare all offers <ChevronRight size={16}/></button></div></div>
 <div className="card impact"><div><b>Impact Dashboard</b><small>Demo metrics</small></div><div className="impactgrid"><div><b>2.4×</b><span>Farmer earning potential</span></div><div><b>3 → 1</b><span>Intermediary stages</span></div><div><b>₹15/kg</b><span>Illustrative price difference</span></div><div><b>18%</b><span>Logistics optimization</span></div></div></div></>
}
function Produce({listed,setListed,notify}){return <><Top eyebrow="FARMER WORKSPACE" title="My Produce" desc="List your harvest and let verified buyers discover it."><button className="primary" onClick={()=>setListed(true)}><Plus size={17}/> List New Produce</button></Top>{listed&&<div className="success"><CheckCircle2/> Wheat listing created successfully. AI matching is now searching for buyers.</div>}<div className="formcard"><div className="formgrid">{["Crop name","Crop variety","Quantity (kg)","Quality / grade","Harvest date","Expected price (₹/kg)","Location","Available-from date"].map((x,i)=><label key={x}>{x}<input defaultValue={i===0?"Wheat":i===1?"Sharbati":i===2?"500":i===3?"A":i===5?"25":i===6?"Indore, Madhya Pradesh":""} placeholder={"Enter "+x.toLowerCase()}/></label>)}</div><label className="full">Photos<input type="file"/></label><button className="primary" onClick={()=>setListed(true)}>Publish Produce Listing <ArrowRight size={17}/></button></div></>}
function Marketplace({filtered,search,setSearch,notify}){return <><Top eyebrow="DIRECT MARKETPLACE" title="Find Produce" desc="Compare transparent offers from verified farmers."><div className="marketstat"><b>{filtered.length}</b> listings available</div></Top><div className="filters"><div className="search big"><Search size={18}/><input placeholder="Search wheat, soybean, onion..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{["Crop","Location","Quality","Price"].map(x=><button key={x}>{x} ▾</button>)}</div><div className="cards">{filtered.map(x=><div className="producecard" key={x.id}><div className="cropicon">{x.crop==="Wheat"?"🌾":x.crop==="Onion"?"🧅":x.crop==="Soybean"?"🫘":"🌱"}</div><div className="pcbody"><div className="pcname"><div><h3>{x.crop}</h3><span><ShieldCheck size={14}/> {x.farmer}</span></div><b>₹{x.price}<small>/kg</small></b></div><div className="tags"><span>Grade {x.grade}</span><span>{x.qty} kg</span><span>{x.distance} km</span></div><p><MapPin size={14}/>{x.location} • Harvested {x.harvest}</p><div className="pcactions"><button className="secondary" onClick={()=>notify("Listing details opened")}>View Details</button><button className="primary" onClick={()=>notify("Offer started for "+x.crop)}>Make Offer</button></div></div></div>)}</div></>}
function Offers({accepted,setAccepted,notify}){return <><Top eyebrow="OFFER MANAGEMENT" title="Buyer Offers" desc="Compare multiple verified buyer offers for your produce."/><div className="offerhero"><div><span>Wheat • 500 kg</span><h2>Choose the best direct offer</h2><small>AI recommendations consider price, location, quantity and logistics cost.</small></div><div className="offerprice">₹28–₹29<small>/kg best range</small></div></div><div className="offertable">{offers.map((o,i)=><div className={"offerrow "+(accepted&&i===0?"chosen":"")} key={o[0]}><div className="buyeravatar">{o[0][0]}</div><div className="buyer"><b>{o[0]} <ShieldCheck size={14}/></b><small>Verified buyer • Direct demand</small></div><div><b>₹{o[1]}/kg</b><small>₹{o[1]*500} total</small></div><div className="matchpct"><b>{o[2]}%</b><small>AI match</small></div><div className="offeractions">{accepted&&i===0?<span className="accepted"><CheckCircle2 size={16}/> Accepted</span>:<><button className="secondary" onClick={()=>notify("Counter offer mode opened")}>Counter</button><button className="primary" onClick={()=>{setAccepted(true);notify("Offer accepted. Order created.")}}>Accept</button></>}</div></div>)}</div></>}
function Orders({accepted}){return <><Top eyebrow="ORDERS" title="Transaction Overview" desc="Track direct farmer-buyer transactions from offer to payment."/><div className="ordercard"><div><span className="pill greenpill">{accepted?"ORDER CONFIRMED":"DEMO ORDER"}</span><h2>Wheat • 500 kg</h2><p>Ramesh Kumar → AgroMart Pvt Ltd</p></div><div className="bigmoney">₹14,000<small>Produce value</small></div></div><div className="card"><div className="cardhead"><b>Transparent transaction breakdown</b><small>Every rupee is visible</small></div><div className="breakdown">{[["Produce value","₹14,000"],["Logistics cost","₹1,200"],["Platform/service fee","₹280"],["Final buyer payment","₹15,480"],["Farmer earnings","₹14,000"]].map(x=><div><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></>}
function Logistics({accepted}){return <><Top eyebrow="LOGISTICS" title="Order Tracking" desc="Coordinate pickup and delivery with transparent logistics costs."/><div className="logcard"><div className="route"><div><span>Pickup</span><b>Indore, MP</b></div><ArrowRight/><div><span>Destination</span><b>Delhi NCR</b></div></div><div className="logmeta"><div><span>Estimated distance</span><b>742 km</b></div><div><span>Transport cost</span><b>₹1,200</b></div><div><span>Pickup date</span><b>26 Aug 2026</b></div><div><span>Status</span><b>{accepted?"Vehicle Assigned":"Order Pending"}</b></div></div></div><div className="timeline">{["Order Confirmed","Vehicle Assigned","Pickup Completed","In Transit","Delivered"].map((x,i)=><div className={accepted&&i<2?"done":""} key={x}><span>{accepted&&i<2?<CheckCircle2/>:<i/>}</span><b>{x}</b><small>{accepted&&i<2?"Completed":"Pending"}</small></div>)}</div></>}
function Analytics(){return <><Top eyebrow="FARMER ANALYTICS" title="Earnings & Market Intelligence" desc="Understand selling prices, demand and direct-market performance."/><div className="chartgrid"><div className="card chart"><div className="cardhead"><div><b>Average Wheat Selling Price</b><small>₹/kg • Demo data</small></div><strong>₹25/kg</strong></div><ResponsiveContainer width="100%" height={230}><LineChart data={trend}><XAxis dataKey="m"/><YAxis/><Tooltip/><Line type="monotone" dataKey="p" strokeWidth={3}/></LineChart></ResponsiveContainer></div><div className="card chart"><div className="cardhead"><div><b>Monthly Earnings</b><small>₹ lakh • Demo data</small></div><strong>₹2.8L</strong></div><ResponsiveContainer width="100%" height={230}><BarChart data={[{m:"Mar",v:1.8},{m:"Apr",v:2.1},{m:"May",v:2.4},{m:"Jun",v:2.2},{m:"Jul",v:2.7},{m:"Aug",v:2.8}]}><XAxis dataKey="m"/><YAxis/><Tooltip/><Bar dataKey="v"/></BarChart></ResponsiveContainer></div></div><div className="stats"><div className="stat"><b>+18%</b><span>Price improvement</span></div><div className="stat"><b>12</b><span>Direct buyers</span></div><div className="stat"><b>4,850 kg</b><span>Total sold</span></div><div className="stat"><b>₹1.2L</b><span>Logistics saved</span></div></div></>}
function Suppliers(){return <><Top eyebrow="BUYER WORKSPACE" title="Saved Suppliers" desc="Verified farmers and reliable direct supply relationships."/><div className="cards">{["Ramesh Kumar • Wheat","Sunita Devi • Soybean","Mohan Lal • Onion"].map(x=><div className="supplier"><div className="buyeravatar">{x[0]}</div><div><h3>{x.split(" • ")[0]}</h3><p>{x.split(" • ")[1]} • <span className="green">Verified Farmer</span></p></div><button className="secondary">View Profile</button></div>)}</div></>}
createRoot(document.getElementById("root")).render(<App/>);
